### ISSUE TITLE
Other languages

### ISSUE THREAD

**Issue by DonaldTsang** [andyburke/simplecoder#2]
What about French? Dutch? German? Swedish? Polish? Russian? Serbian? Italian?

**Comment by andyburke** [comment]
Would be extremely glad to accept pull requests adding other languages. If you know a different language and could help choose short, easy, dissimilar words and submit a PR I would be very psyched!

**Comment by DonaldTsang** [comment]
@andyburke was hoping that this becomes an open topic for people to discuss such solutions
